import { uid } from './constants';
import type { DesignElement, InvoiceDesign, TableColumn } from './types';

function el(partial: Partial<DesignElement> & Pick<DesignElement, 'type' | 'name'>): DesignElement {
  return {
    id: uid(),
    x: 40,
    y: 40,
    width: 200,
    height: 40,
    angle: 0,
    opacity: 1,
    locked: false,
    visible: true,
    zIndex: 0,
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '400',
    fontStyle: 'normal',
    textAlign: 'left',
    fill: '#333333',
    stroke: '#cccccc',
    strokeWidth: 1,
    lineHeight: 1.2,
    charSpacing: 0,
    ...partial,
  };
}

const defaultColumns: TableColumn[] = [
  { id: uid('col'), key: 'item', label: 'Description', width: 40, align: 'left' },
  { id: uid('col'), key: 'qty', label: 'Qty', width: 12, align: 'right' },
  { id: uid('col'), key: 'price', label: 'Unit Price', width: 18, align: 'right' },
  { id: uid('col'), key: 'tax', label: 'Tax', width: 12, align: 'right' },
  { id: uid('col'), key: 'amount', label: 'Amount', width: 18, align: 'right' },
];

export function createDefaultInvoiceTemplate(name = 'Classic Invoice'): InvoiceDesign {
  const now = new Date().toISOString();
  const elements: DesignElement[] = [
    el({
      type: 'placeholder',
      name: 'Company Logo',
      placeholder: 'company_logo',
      x: 40,
      y: 36,
      width: 120,
      height: 60,
      zIndex: 1,
    }),
    el({
      type: 'placeholder',
      name: 'Company Name',
      placeholder: 'company_name',
      x: 480,
      y: 40,
      width: 280,
      height: 32,
      fontSize: 22,
      fontWeight: '700',
      textAlign: 'right',
      zIndex: 2,
    }),
    el({
      type: 'placeholder',
      name: 'Company Address',
      placeholder: 'company_address',
      x: 480,
      y: 78,
      width: 280,
      height: 70,
      fontSize: 11,
      textAlign: 'right',
      fill: '#666666',
      zIndex: 3,
    }),
    el({
      type: 'text',
      name: 'Title',
      text: 'TAX INVOICE',
      x: 40,
      y: 120,
      width: 200,
      height: 36,
      fontSize: 26,
      fontWeight: '700',
      fill: '#2389d6',
      zIndex: 4,
    }),
    el({
      type: 'placeholder',
      name: 'Customer Name',
      placeholder: 'customer_name',
      x: 40,
      y: 180,
      width: 320,
      height: 28,
      fontSize: 16,
      fontWeight: '600',
      zIndex: 5,
    }),
    el({
      type: 'placeholder',
      name: 'Customer Address',
      placeholder: 'customer_address',
      x: 40,
      y: 214,
      width: 320,
      height: 80,
      fontSize: 12,
      fill: '#555555',
      zIndex: 6,
    }),
    el({
      type: 'placeholder',
      name: 'Invoice Number',
      placeholder: 'invoice_number',
      x: 520,
      y: 180,
      width: 240,
      height: 24,
      fontSize: 13,
      textAlign: 'right',
      zIndex: 7,
    }),
    el({
      type: 'placeholder',
      name: 'Invoice Date',
      placeholder: 'invoice_date',
      x: 520,
      y: 210,
      width: 240,
      height: 24,
      fontSize: 13,
      textAlign: 'right',
      zIndex: 8,
    }),
    el({
      type: 'placeholder',
      name: 'Due Date',
      placeholder: 'due_date',
      x: 520,
      y: 240,
      width: 240,
      height: 24,
      fontSize: 13,
      textAlign: 'right',
      zIndex: 9,
    }),
    el({
      type: 'itemsTable',
      name: 'Line Items',
      placeholder: 'items_table',
      x: 40,
      y: 320,
      width: 714,
      height: 280,
      columns: defaultColumns.map((c) => ({ ...c, id: uid('col') })),
      showHeader: true,
      showTotals: false,
      headerBg: '#2389d6',
      headerColor: '#ffffff',
      borderColor: '#dcdcdc',
      rowHeight: 32,
      fontSize: 12,
      zIndex: 10,
    }),
    el({
      type: 'placeholder',
      name: 'Subtotal',
      placeholder: 'subtotal',
      x: 560,
      y: 640,
      width: 194,
      height: 24,
      fontSize: 13,
      textAlign: 'right',
      zIndex: 11,
    }),
    el({
      type: 'placeholder',
      name: 'Tax',
      placeholder: 'tax',
      x: 560,
      y: 670,
      width: 194,
      height: 24,
      fontSize: 13,
      textAlign: 'right',
      zIndex: 12,
    }),
    el({
      type: 'placeholder',
      name: 'Grand Total',
      placeholder: 'grand_total',
      x: 560,
      y: 710,
      width: 194,
      height: 32,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'right',
      fill: '#2389d6',
      zIndex: 13,
    }),
    el({
      type: 'placeholder',
      name: 'Amount in Words',
      placeholder: 'amount_in_words',
      x: 40,
      y: 640,
      width: 480,
      height: 60,
      fontSize: 12,
      fill: '#555555',
      zIndex: 14,
    }),
    el({
      type: 'line',
      name: 'Divider',
      x: 40,
      y: 310,
      width: 714,
      height: 2,
      stroke: '#dcdcdc',
      strokeWidth: 1,
      zIndex: 0,
    }),
  ];

  return {
    id: uid('design'),
    name,
    version: 1,
    page: { width: 794, height: 1123, background: '#ffffff', margin: 40 },
    elements,
    grid: { enabled: true, size: 10, snap: true },
    createdAt: now,
    updatedAt: now,
  };
}

export function createBlankTemplate(name = 'Blank Invoice'): InvoiceDesign {
  const now = new Date().toISOString();
  return {
    id: uid('design'),
    name,
    version: 1,
    page: { width: 794, height: 1123, background: '#ffffff', margin: 40 },
    elements: [],
    grid: { enabled: true, size: 10, snap: true },
    createdAt: now,
    updatedAt: now,
  };
}

export const TEMPLATE_PRESETS = [
  { id: 'classic', label: 'Classic Invoice', factory: () => createDefaultInvoiceTemplate('Classic Invoice') },
  { id: 'blank', label: 'Blank Canvas', factory: () => createBlankTemplate('Blank Invoice') },
];
